export const DEFAULT_CATEGORIES = [
  { name: "HUD & Gameplay", slug: "hud-gameplay" },
  { name: "Main Menu", slug: "main-menu" },
  { name: "Settings", slug: "settings" },
  { name: "Inventory", slug: "inventory" },
  { name: "Shop & Marketplace", slug: "shop-marketplace" },
  { name: "Character Customization", slug: "character-customization" },
  { name: "Lobby & Server Select", slug: "lobby-server-select" },
  { name: "Leaderboard & Stats", slug: "leaderboard-stats" },
  { name: "Chat & Social", slug: "chat-social" },
  { name: "Tutorial & Onboarding", slug: "tutorial-onboarding" },
  { name: "Loading Screen", slug: "loading-screen" },
  { name: "Dialogue & NPC", slug: "dialogue-npc" },
  { name: "Map & Navigation", slug: "map-navigation" },
  { name: "Quest & Objectives", slug: "quest-objectives" },
  { name: "Upgrade & Skills", slug: "upgrade-skills" },
  { name: "Notifications & Popups", slug: "notifications-popups" },
  { name: "Trading", slug: "trading" },
  { name: "Battle & Combat", slug: "battle-combat" },
];
